<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>OpenLabStudio.plugins</RootNamespace>
	<Version>1.0.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
	<Company>Gexy</Company>
	<Authors>Eugenio Liguori</Authors>
	<PackageProjectUrl>https://github.com/GexyLab/ols-plugins/tree/main/Projects%20directory</PackageProjectUrl>
	<AssemblyName>OpenLabStudio Plugin Projects Directory</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="GeJSON">
      <HintPath>..\..\OpenLab Studio\OpenLab Studio\lib\GeJSON.dll</HintPath>
    </Reference>
    <Reference Include="ol-sdk">
      <HintPath>..\..\OpenLab Studio\OpenLab Studio\lib\ol-sdk.dll</HintPath>
    </Reference>
    <Reference Include="OpenLabSDK">
      <HintPath>..\..\OpenLab Studio\OpenLab Studio\lib\OpenLabSDK.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
