<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenLabStudio.plugins</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="GeJSON">
      <HintPath>lib\GeJSON.dll</HintPath>
    </Reference>
    <Reference Include="OpenLabSDK">
      <HintPath>lib\OpenLabSDK.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
